# Generated by Django 5.2.16 on 2026-09-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_email_verification_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationotp",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
