# Generated by Django 5.2.16 on 2026-09-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_emailverificationotp_locked_until"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailverificationotp",
            name="attempts",
        ),
        migrations.RemoveField(
            model_name="emailverificationotp",
            name="locked_until",
        ),
    ]
