# Generated by Django 5.2.16 on 2026-09-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_passwordresetotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationotp",
            name="verification_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="passwordresetotp",
            name="verification_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
