# Generated by Django 5.2.16 on 2026-09-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_google_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwordresetotp",
            name="verification_attempts",
        ),
    ]
