# Generated by Django 5.2.16 on 2026-09-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_passwordresetotp_verification_attempts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailverificationotp",
            name="verification_attempts",
        ),
    ]
