# Generated by Django 5.2.16 on 2026-09-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_studentprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentProfile",
        ),
    ]
