# Generated by Django 5.2.16 on 2026-10-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_delete_studentprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default_profile.png",
                upload_to="profile_images/",
            ),
        ),
    ]
