# Generated by Django 5.2.16 on 2026-10-02 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=150)),
                ("short_bio", models.TextField(max_length=1000)),
                (
                    "years_of_experience",
                    models.CharField(
                        choices=[
                            ("less_than_one", "Less than 1 year"),
                            ("one_to_three", "1–3 years"),
                            ("three_to_five", "3–5 years"),
                            ("five_to_ten", "5–10 years"),
                            ("ten_plus", "10+ years"),
                        ],
                        max_length=20,
                    ),
                ),
                ("topics_to_teach", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "instructor_profiles",
            },
        ),
        migrations.CreateModel(
            name="InstructorApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "years_of_experience",
                    models.CharField(
                        choices=[
                            ("less_than_one", "Less than 1 year"),
                            ("one_to_three", "1–3 years"),
                            ("three_to_five", "3–5 years"),
                            ("five_to_ten", "5–10 years"),
                            ("ten_plus", "10+ years"),
                        ],
                        max_length=20,
                    ),
                ),
                ("topics_to_teach", models.TextField()),
                ("short_bio", models.TextField(max_length=1000)),
                ("motivation", models.TextField(max_length=2000)),
                ("linkedin_url", models.URLField(blank=True, max_length=255)),
                ("github_url", models.URLField(blank=True, max_length=255)),
                ("personal_website", models.URLField(blank=True, max_length=255)),
                (
                    "resume",
                    models.FileField(upload_to="instructor_applications/resumes/"),
                ),
                ("terms_accepted", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_message", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_instructor_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "instructor_applications",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-submitted_at"],
                        name="instr_app_status_date_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("user",),
                        name="unique_pending_instructor_application_per_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "approved")),
                        fields=("user",),
                        name="unique_approved_instructor_application_per_user",
                    ),
                ],
            },
        ),
    ]
