# Generated by Django 5.2.16 on 2026-10-04 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(upload_to="instructor_applications/documents/"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "instructor_application_documents",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="instructorapplication",
            name="instr_app_status_date_idx",
        ),
        migrations.RenameField(
            model_name="instructorapplication",
            old_name="personal_website",
            new_name="portfolio_url",
        ),
        migrations.AddField(
            model_name="instructorapplication",
            name="education",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="instructorapplication",
            name="location",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="became_instructor_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="education",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="github_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="location",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="occupation",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="portfolio_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="instructorapplication",
            name="topics_to_teach",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="instructorprofile",
            name="job_title",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="instructorprofile",
            name="short_bio",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="instructorprofile",
            name="topics_to_teach",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="instructorprofile",
            name="years_of_experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("less_than_one", "Less than 1 year"),
                    ("one_to_three", "1–3 years"),
                    ("three_to_five", "3–5 years"),
                    ("five_to_ten", "5–10 years"),
                    ("ten_plus", "10+ years"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="instructorapplicationdocument",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supporting_documents",
                to="instructors.instructorapplication",
            ),
        ),
    ]
