# Generated by Django 5.2.16 on 2026-10-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0002_instructorapplicationdocument_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instructorapplication",
            old_name="topics_to_teach",
            new_name="categories_to_teach",
        ),
        migrations.RenameField(
            model_name="instructorprofile",
            old_name="topics_to_teach",
            new_name="categories_to_teach",
        ),
    ]
