# Generated by Django 5.2.16 on 2026-10-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "instructors",
            "0003_rename_topics_to_teach_instructorapplication_categories_to_teach_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructorprofile",
            name="occupation",
        ),
    ]
