# Generated by Django 5.2.16 on 2026-10-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0004_remove_instructorprofile_occupation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructorapplication",
            name="job_title",
        ),
        migrations.AddField(
            model_name="instructorapplication",
            name="occupation",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
