# Generated by Django 5.2.16 on 2026-10-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0005_remove_instructorapplication_job_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instructorprofile",
            old_name="job_title",
            new_name="occupation",
        ),
    ]
