# Generated by Django 5.2.16 on 2026-10-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0006_rename_job_title_instructorprofile_occupation"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorapplication",
            name="full_name",
            field=models.CharField(default="Unknown", max_length=150),
        ),
        migrations.AddField(
            model_name="instructorapplication",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="instructor_applications/profile_images/",
            ),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="full_name",
            field=models.CharField(default="Unknown", max_length=150),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="instructor_profiles/"
            ),
        ),
    ]
