# Generated by Django 5.2.16 on 2026-10-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("instructors", "0007_instructorapplication_full_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructorapplication",
            name="categories_to_teach",
        ),
        migrations.RemoveField(
            model_name="instructorprofile",
            name="categories_to_teach",
        ),
        migrations.AddField(
            model_name="instructorapplication",
            name="categories_to_teach",
            field=models.ManyToManyField(
                blank=True,
                related_name="instructor_applications",
                to="categories.category",
            ),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="categories_to_teach",
            field=models.ManyToManyField(
                blank=True, related_name="instructor_profiles", to="categories.category"
            ),
        ),
    ]
