# Generated by Django 5.2.16 on 2026-10-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "instructors",
            "0008_remove_instructorapplication_categories_to_teach_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorapplication",
            name="admin_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
