# Generated by Django 5.2.16 on 2026-10-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0009_alter_instructorapplication_admin_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorapplication",
            name="motivation",
            field=models.TextField(max_length=1000),
        ),
    ]
