# Generated by Django 5.2.16 on 2026-10-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0010_alter_instructorapplication_motivation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instructorapplication",
            old_name="short_bio",
            new_name="professional_bio",
        ),
        migrations.RenameField(
            model_name="instructorprofile",
            old_name="short_bio",
            new_name="professional_bio",
        ),
    ]
