# Generated by Django 5.2.16 on 2026-09-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="github_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
