# Generated by Django 5.2.16 on 2026-10-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_studentprofile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
