# Generated by Django 5.2.16 on 2026-10-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_alter_studentprofile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="profile_image",
        ),
    ]
