# Generated by Django 5.2.16 on 2026-10-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="plan_type",
            field=models.CharField(
                choices=[("free", "Free"), ("premium", "Premium")], max_length=20
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("plan_type", "free")),
                fields=("plan_type",),
                name="unique_free_plan_type",
            ),
        ),
    ]
