# Generated by Django 5.2.16 on 2026-10-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_subscriptionplan_plan_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={"ordering": ["-created_at"]},
        ),
    ]
