# Generated by Django 5.2.16 on 2026-10-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_subscriptionplan_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="benefits",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="description",
            field=models.TextField(),
        ),
    ]
